name: Run Scheduled Task
on:
  schedule:
    - cron: '*/2 * * * *' # Every 2 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  call-vercel-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: |
          curl -X GET "https://image-recognition-system-git-test-cron-github-keldens-projects.vercel.app/test" 